# https://github.com/microsoft/winget-dsc
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

properties:
  resources:
    - resource: PSDscResources/Script
      id: Microsoft.WinGet.Client
      directives:
        description: Microsoft.WinGet.DSC/WinGetPackage requires the Microsoft.WinGet.Client module to be installed.
      settings:
        SetScript: |
          Install-Module -Name Microsoft.WinGet.Client -Force -Repository PSGallery | Out-Null;
        GetScript: |
          Get-Module -ListAvailable -Name Microsoft.WinGet.Client
        TestScript: |
          $modules = Get-Module -ListAvailable -Name Microsoft.WinGet.Client
          return $modules.Count -gt 0
    # $HOME\.local\bin 경로를 PATH에 추가
    - resource: PSDscResources/Script
      settings:
        GetScript: return $false
        TestScript: |
          $userEnv = [System.Environment]::GetEnvironmentVariable("PATH", "User");
          return $userEnv.Split(";") -contains "$HOME\.local\bin"
        SetScript: |
          $userEnv = [System.Environment]::GetEnvironmentVariable("PATH", "User");
          [System.Environment]::SetEnvironmentVariable("PATH", "$userEnv;$HOME\.local\bin", "User");


    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vscode
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: powershell
      settings:
        id: Microsoft.PowerShell
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: windows-terminal
      settings:
        id: Microsoft.WindowsTerminal
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: firefox
      settings:
        id: Mozilla.Firefox
        source: winget
    
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: fzf
      settings:
        id: junegunn.fzf
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: starship
      settings:
        id: Starship.Starship
        source: winget
    - resource: PSDscResources/Script
      id: psfzf
      settings:
        GetScript: return $false
        TestScript: |
          $modules = Get-Module -ListAvailable -Name PSFzf
          return $modules -ne $null
        SetScript: |
          Install-Module -Name PSFzf -Force -Repository PSGallery
    - resource: PSDscResources/Script
      id: powershell-profile
      settings:
        GetScript: return $false
        TestScript: |
          $profilePath = pwsh -NoProfile -Command 'Write-Output $PROFILE'
          Test-Path -Path $profilePath
        SetScript: |
          $profilePath = pwsh -NoProfile -Command 'Write-Output $PROFILE'
          $null = New-Item -ItemType Directory -Force -Path (Split-Path $profilePath)
          Invoke-WebRequest -Uri 'https://gist.githubusercontent.com/lyra95/5ee9fe41cc17518344df4b563884ed0f/raw/$PROFILE' -OutFile $profilePath

  configurationVersion: 0.2.0