# https://github.com/microsoft/winget-dsc
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

properties:
  resources:
    - resource: PSDscResources/Script
      id: Microsoft.WinGet.Client
      directives:
        description: Microsoft.WinGet.DSC/WinGetPackage requires the Microsoft.WinGet.Client module to be installed.
      settings:
        SetScript: |
          Install-Module -Name Microsoft.WinGet.Client -Force -Repository PSGallery | Out-Null;
        GetScript: return $false
        TestScript: return $false

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vscode
      directives:
        description: Install Visual Studio Code
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: powershell
      directives:
        description: Install Powershell
      settings:
        id: Microsoft.PowerShell
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: windows-terminal
      directives:
        description: Install Windows Terminal
      settings:
        id: Microsoft.WindowsTerminal
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: firefox
      directives:
        description: Install firefox
      settings:
        id: Mozilla.Firefox
        source: winget

  configurationVersion: 0.2.0